# Generated by Django 4.1.2 on 2022-11-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('IdK', models.AutoField(primary_key=True, serialize=False)),
                ('LoginK', models.CharField(max_length=20)),
                ('ImieK', models.CharField(max_length=30)),
                ('NazwiskoK', models.CharField(max_length=30)),
                ('HasloK', models.CharField(max_length=64)),
                ('AdresK', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('ISBN', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('TytulKs', models.CharField(max_length=150)),
                ('AutorKs', models.CharField(max_length=255)),
                ('CenaKs', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('IdP', models.AutoField(primary_key=True, serialize=False)),
                ('LoginP', models.CharField(max_length=20)),
                ('ImieP', models.CharField(max_length=30)),
                ('NazwiskoP', models.CharField(max_length=30)),
                ('PeselP', models.CharField(max_length=11)),
                ('DataZatr', models.DateField()),
                ('HasloP', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('IdZ', models.AutoField(primary_key=True, serialize=False)),
                ('DataZ', models.DateField()),
                ('Status', models.CharField(max_length=30)),
                ('IdKs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pracownik_app.ksiazka')),
                ('LoginK', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pracownik_app.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Recenzja',
            fields=[
                ('IdR', models.IntegerField(primary_key=True, serialize=False)),
                ('TrescR', models.CharField(max_length=2000)),
                ('DataWyst', models.DateField()),
                ('IdKs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pracownik_app.ksiazka')),
                ('LoginK', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pracownik_app.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Obserwacja',
            fields=[
                ('IdO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('IdKs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pracownik_app.ksiazka')),
                ('LoginK', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pracownik_app.klient')),
            ],
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='DodalIdP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pracownik_app.pracownik'),
        ),
    ]
