# Generated by Django 3.2.4 on 2023-01-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pracownik_app', '0002_ksiazka_ilosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='recenzja',
            name='Ocena',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
